###########################################################################
##  PowerMaps.gi
##  
##  (C) 2025 Frank Lübeck, Lehrstuhl für Algebra und Zahlentheorie, RWTH Aachen
##  
##  This file provides 'PowerMapsOfAllClasses' for a group G.
##  It returns a list of lists.
##  If x is in ConjugacyClasses(G)[i] of order k then the i-th entry
##  of the result is of length k and the j-th entry is the position of
##  the class of x^(j-1).
##  
##  This implementation tries to minimize the number of conjugacy tests. 
##  
##  There are also a number of applications:
##     MaximalCyclics(G)  indices of classes whose representatives generate
##     the maximal cyclic subgroups up to conjugacy.
##  
##     RationalClassSets(G) subsets of indices of conjugacy classes of G
##     whose representatives generate conjugate cyclic subgroups.
##  
##     InduceAllFromCyclicSubgroup(G, i) all induced characters for irreducibles
##     of cyclic subgroups generated by elements in class i.
##  
##     InducedFromAllMaximalCyclicSubgroups(G) induced characters from all
##     maximal cyclic subgroups of G.
##  
##     PowerMapCharacters(G, n)
##     SmallPowerMapCharacters(G)  a list of generalized characters of G
##     associated to the map g -> g^n on G.
##  

##  <#GAPDoc Label="PowerMapsOfAllClasses">
##  <ManSection>
##  <Attr Name="PowerMapsOfAllClasses" Arg="G"/>
##  <Returns>a list of lists of positive integers</Returns>
##  <Description>
##  Let <A>G</A> be a finite group and number its conjugacy classes as in
##  <C>ConjugacyClasses(<A>G</A>)</C>. If <M>x</M> is a representative of
##  class number <M>i</M> and has order <M>m</M>, then the <M>i</M>-th
##  entry of the returned list is a list of length <M>m</M> whose
##  <M>j</M>-th entry is the number of the class containing
##  <M>x^{{j-1}}</M>, for <M>j = 1, \ldots, m</M> (so the first entry is
##  always <M>1</M>, corresponding to <M>x^0</M>).
##  <P/>
##  In this way the result encodes the power maps of <E>all</E> conjugacy
##  classes of <A>G</A> at once. The implementation tries to minimize the
##  number of, sometimes expensive,  calls to 
##  <Ref Func="PositionConjugacyClass"/>; the algorithm computes the
##  orbit of the class of <M>x</M> under the action of the unit group
##  of the integers modulo <M>m</M>.
##  <Example>
##  gap> G := AlternatingGroup(5);;
##  gap> List(ConjugacyClasses(G), c-> Order(Representative(c)));
##  [ 1, 2, 3, 5, 5 ]
##  gap> PowerMapsOfAllClasses(G);
##  [ [ 1 ], [ 1, 2 ], [ 1, 3, 3 ], [ 1, 4, 5, 5, 4 ], [ 1, 5, 4, 4, 5 ] ]
##  </Example>
##  Several other attributes and functions in this package are implemented using
##  <Ref Attr="PowerMapsOfAllClasses"/>.
##  </Description>
##  </ManSection>
##  <#/GAPDoc>
InstallMethod(PowerMapsOfAllClasses, ["IsGroup"], function(G)
  local cls, reps, ords, sords, perm, res, o, ps, gens, s, orb, 
        trans, stab, ostab, ng, g, og, trg, orbg, excl, m, pos, 
        x, y, xo, norb, ntrans, t, map, k, mapk, i, l, e, j, p;
  cls := ConjugacyClasses(G);
  reps := List(cls, Representative);
  ords := List(reps, Order);
  sords := ShallowCopy(ords);
  perm := [1..Length(cls)];
  SortParallel(sords, perm);

  res := [];
  # we start with small orders
  for i in perm do
    if not IsBound(res[i]) then
      o := ords[i];
      if o = 1 then
        res[i] := [i];
        continue;
      fi;
      ps := Set(Factors(o));

      # first the rational class of reps[i] 
      # (classes of reps[i]^k with gcd(k, o) = 1, we use action of
      # (Z/oZ)^x on classes and compute orbit and stabilizer)
      gens := Flat(GeneratorsPrimeResidues(o).generators);
      # order of group and found subgroup of stabilizer
      s := Phi(o);
      # start the orbit, stabilizer and transversal
      orb := [i];
      trans := [1];
      stab := BlistList([1..o], [1]);
      ostab := 1;
      ng := 0;
      # now we extend this generator wise
      while Length(orb)*ostab < s do
        ng := ng+1;
        g := gens[ng];
        og := OrderMod(g, o);
        # orbit of this generator on the start point
        # until we reach a known point
        trg := [1];
        orbg := [i];
        for k in [1..og] do
          # we can exclude some classes as next image
          if og mod k = 0 then
            # next point cannot be in current g-orbit, except start point
            excl := orbg{[2..Length(orbg)]};
            m := PositionConjugacyClass(G, reps[orbg[k]]^g, excl);
            pos := Position(orb, m);
            if pos = fail then
              # found new class
              Add(orbg, m);
              Add(trg, trg[k]*g mod o);
            else
              # found class in orbit of the previous generators
              # and so an element in stabilizer of i
              x := (trans[pos] * g^-k) mod o;
              y := x;
              xo := 1;
              while not stab[y] do
                y := (y*x) mod o;
                xo := xo+1;
              od;
              for l in [1..o] do
                if stab[l] then
                  y := (l*x) mod o;
                  for e in [1..xo-1] do
                    stab[y] := true;
                    y := (y*x) mod o;
                  od;
                fi;
              od;
              ostab := ostab*xo;
              # Now we know the full orbit of the subgroup of the generators
              # considered so far. We leave this loop and write them down
              # afterwards.
              break;
            fi;
          else
            # next point is certainly not yet known
            excl := Concatenation(orb,orbg);
            x := PositionConjugacyClass(G, reps[orbg[k]]^g, excl);
            Add(orbg, x);
            Add(trg, trg[k]*g mod o);
          fi;
        od;
        # we get the new elements in the orbit by applying the
        # non-trivial elements in trg to those in orb
        norb := [];
        ntrans := [];
        excl := Concatenation(orb, orbg);
        for j in [2..Length(orbg)] do
          Add(norb, orbg[j]);
          t := trg[j];
          Add(ntrans, t);
          for m in [2..Length(orb)] do
            # we know to get a new class
            x := PositionConjugacyClass(G, reps[orb[m]]^t, excl);
            Add(norb, x);
            Add(ntrans, (trans[m]*t) mod o);
            Add(excl, x);
          od;
        od;
        Append(orb, norb);
        Append(trans, ntrans);
      od;
      map := [];
      map[o] := perm[1];
      for j in [1..o] do
        if stab[j] then
          for k in [1..Length(orb)] do
            map[(j*trans[k]) mod o] := orb[k];
          od;
        fi;
      od;

      # the rest we get from smaller order classes (already done)
      for p in ps do
        k := o/p;
        pos := PositionConjugacyClass(G, reps[i]^p);
        mapk := res[pos];
        for j in [1..k-1] do
          map[(p*j) mod o] := mapk[j];
        od;
      od;
      res[i] := map;

      # and we get the maps for the other classes in the same rational class
      for j in [2..Length(orb)] do
        mapk := [];
        for k in [1..o-1] do
          mapk[k] := map[(trans[j]*k) mod o];
        od;
        mapk[o] := perm[1];
        res[orb[j]] := mapk;
      od;
    fi;
  od;

  # so far we have in res[i][k] the class of reps[i]^k,
  # now we shift it to reps[i]^(k-1), so that the trivial class comes first
  res := List(res, a-> Concatenation([a[Length(a)]],a{[1..Length(a)-1]}));

  return res;
end);


##  <#GAPDoc Label="InduceAllFromCyclicSubgroup">
##  <ManSection>
##  <Func Name="InduceAllFromCyclicSubgroup" Arg="G, i"/>
##  <Func Name="InduceAllFromCyclicSubgroup" Arg="CCT, i"/>
##  <Returns>a list of row vectors of cyclotomic numbers</Returns>
##  <Description>
##  In the first form <A>G</A> is a group. In the second form <A>CCT</A>
##  is an <Ref Filt="IsCCTable"/> object of a group.
##  Let <A>i</A> be the number of one of its conjugacy classes.
##  This function returns the pairwise distinct characters of the group
##  induced from the linear characters of the cyclic subgroup generated by
##  a representative of class <A>i</A> (as lists of values, not as 
##  class function objects).
##  <P/>
##  In the first form each value is the list of character values in the order
##  of <C>ConjugacyClasses(<A>G</A>)</C>.
##  <P/>
##  In the second form  each vector instead has one entry for
##  every <E>rational</E> class of the group, in the order given by
##  <Ref Attr="RationalClassSets"/> (i.e., conjugacy classes belonging to
##  the same rational class share one entry).
##  <Example>
##  gap> G := AlternatingGroup(5);;
##  gap> T := CCTable(G);;
##  gap> InduceAllFromCyclicSubgroup(G, 4);
##  [ [ 12, 0, 0, 2, 2 ], [ 12, 0, 0, E(5)+E(5)^4, E(5)^2+E(5)^3 ],
##    [ 12, 0, 0, E(5)^2+E(5)^3, E(5)+E(5)^4 ] ]
##  gap> InduceAllFromCyclicSubgroup(T, 4);
##  [ [ 12, 0, 0, 2 ], [ 12, 0, 0, E(5)+E(5)^4 ],
##    [ 12, 0, 0, E(5)^2+E(5)^3 ] ]
##  </Example>
##  </Description>
##  </ManSection>
##  <#/GAPDoc>
# all induced characters of linear characters of the cyclic group
# generated by an element in class i
BindGlobal("InduceAllFromCyclicSubgroup", function(GorCCT, i)
  local cls, ncl, pm, cen, o, I, inds, len, store, chorb, null, 
        res, k, ch, l, a, j;
  cls := ConjugacyClasses(GorCCT);
  ncl := Length(cls);
  pm := PowerMapsOfAllClasses(GorCCT)[i];
  cen := [];
  for j in pm do
    cen[j] := Size(GorCCT)/Size(cls[j]);
  od;
  o := Length(pm);
  I := Positions(pm, i)-1;
  if IsCCTable(GorCCT) then
    inds := List(RationalClassSets(GorCCT), a-> a[1]);
    len := Length(inds);
    store := ListWithIdenticalEntries(ncl, fail);
    store{inds} := [1..len];
  else
    store := [1..ncl];
    inds := store;
    len := ncl;
  fi;

  # some linear characters obviously yield the same induced character
  chorb := Set(List([0..o-1], j-> Set((j*I) mod o)));

  null := 0*[1..len];
  res := [];
  for a in chorb do
    k := a[1];
    ch := ShallowCopy(null);
    for j in [0..o-1] do
      l := pm[j+1];
      a := store[l];
      if a <> fail then
        ch[a] := ch[a] + cen[l]/o * E(o)^(j*k);
      fi;
    od;
    Add(res, ch);
  od;
  return res;
end);

##  <#GAPDoc Label="MaximalCyclics">
##  <ManSection>
##  <Attr Name="MaximalCyclics" Arg="G"/>
##  <Returns>a list of positive integers</Returns>
##  <Description>
##  Returns a list <M>l</M> of class numbers such that the representatives
##  of the classes <M>i \in l</M> generate representatives of the maximal
##  cyclic subgroups (that is cyclic subgroups not contained in larger cyclic
##  subgroups) of <A>G</A>, up to conjugacy. The returned numbers are
##  always first entries of the lists in <Ref Attr="RationalClassSets"/>.
##  <Example>
##  gap> MaximalCyclics(AlternatingGroup(5));
##  [ 4, 3, 2 ]
##  </Example>
##  </Description>
##  </ManSection>
##  <#/GAPDoc>
# Returns list l of indices such that reps of classes i, i in l,
# generate representatives of maximal cyclic subgroups,
# the returned classes are first entries in RationalClassSets(G)
InstallMethod(MaximalCyclics, ["IsGroup"], function(G)
  local pms, rs, f, ords, k, l, bl, res, i, j, m;
  pms := PowerMapsOfAllClasses(G);
  rs := RationalClassSets(G);
  f := List(rs, a-> a[1]);
  ords := List(pms, Length);
  k := Length(pms);
  l := [1..k];
  SortParallel(ords, l);
  bl := BlistList([1..k], []);
  res := [];
  for j in [k,k-1..1] do
    i := l[j];
    if i in f then
      if not bl[i] then
        Add(res, i);
        for m in pms[i] do
          bl[m] := true;
        od;
      fi;
    fi;
  od;
  return res;
end);

##  <#GAPDoc Label="InducedFromAllMaximalCyclicSubgroups">
##  <ManSection>
##  <Func Name="InducedFromAllMaximalCyclicSubgroups" Arg="G"/>
##  <Returns>a list of row vectors of cyclotomic numbers</Returns>
##  <Description>
##  Returns the set of all characters of <A>G</A> induced from irreducible
##  characters of the maximal cyclic subgroups of <A>G</A>, computed via
##  <Ref Attr="MaximalCyclics"/> and
##  <Ref Func="InduceAllFromCyclicSubgroup"/>. These characters always span
##  the vector space of class functions on <A>G</A>.
##  <Example>
##  gap> G := AlternatingGroup(5);;
##  gap> indcyc := InducedFromAllMaximalCyclicSubgroups(G);
##  [ [ 12, 0, 0, 2, 2 ], [ 12, 0, 0, E(5)^2+E(5)^3, E(5)+E(5)^4 ],
##    [ 12, 0, 0, E(5)+E(5)^4, E(5)^2+E(5)^3 ], [ 20, 0, -1, 0, 0 ],
##    [ 20, 0, 2, 0, 0 ], [ 30, -2, 0, 0, 0 ], [ 30, 2, 0, 0, 0 ] ]
##  gap> Rank(indcyc);
##  5
##  </Example>
##  </Description>
##  </ManSection>
##  <#/GAPDoc>
# induced characters of all irreducibles of maximal cyclic subgroups
# (these always span the space of all class functions over the rational
# numbers)
BindGlobal("InducedFromAllMaximalCyclicSubgroups", function(G)
  local res, i;
  res := [];
  for i in MaximalCyclics(G) do
    Append(res, InduceAllFromCyclicSubgroup(G, i));
  od;
  return Set(res);
end);

##  <#GAPDoc Label="RationalClassSets">
##  <ManSection>
##  <Attr Name="RationalClassSets" Arg="G"/>
##  <Returns>a list of lists of positive integers</Returns>
##  <Description>
##  Returns a list of lists, where each inner list is the set of numbers
##  of the conjugacy classes of <A>G</A> whose representatives generate
##  conjugate cyclic subgroups (i.e., the union of these classes is a single
##  <E>rational class</E>). The outer list is sorted by
##  increasing element order and then by increasing class length. The
##  first entry of each inner list can be used as a canonical
##  representative number for that rational class.
##  <Example>
##  gap> G := AlternatingGroup(5);;
##  gap> List(ConjugacyClasses(G), c-> Order(Representative(c)));
##  [ 1, 2, 3, 5, 5 ]
##  gap> RationalClassSets(G);
##  [ [ 1 ], [ 2 ], [ 3 ], [ 4, 5 ] ]
##  </Example>
##  </Description>
##  </ManSection>
##  <#/GAPDoc>
# returns list of lists where each entry is the list of positions of the
# conjugacy classes in one rational class (i.e., the cyclic subgroups
# generated by elements in these classes are conjugate).
InstallMethod(RationalClassSets, ["IsGroup"], function(G)
  local pms, cls, ords, k, bl, res, s, i, j;
  pms := PowerMapsOfAllClasses(G);
  cls := List(ConjugacyClasses(G), Size);
  ords := List(pms, Length);
  k := Length(pms);
  bl := BlistList([1..k], []);
  res := [];
  for i in [1..k] do
    if not bl[i] then
      s := [];
      for j in [1..Length(pms[i])] do
        if Gcd(ords[i], j-1) = 1 then
          Add(s, pms[i][j]);
          bl[pms[i][j]] := true;
        fi;
      od;
      Add(res, Set(s));
    fi;
  od;
  # reorder by element order and class length
  SortParallel(List(res, a-> [ords[a[1]],cls[a[1]]]), res);
  return res;
end);
##  <#GAPDoc Label="NrRationalClasses">
##  <ManSection>
##  <Attr Name="NrRationalClasses" Arg="G"/>
##  <Returns>a non-negative integer</Returns>
##  <Description>
##  Returns the number of rational classes of the finite group <A>G</A>.
##  <Example>
##  gap> NrRationalClasses(AlternatingGroup(5));
##  4
##  </Example>
##  </Description>
##  </ManSection>
##  <#/GAPDoc>
InstallMethod(NrRationalClasses, ["IsGroup"],
  G-> Length(RationalClassSets(G)));

##  This function returns a list of lists of integers. Each entry is of form
##  [i, j, k2, ..., km] where i is the number of a class x^G, j is the number of
##  the class of x^-1, m is the number of conjugacy classes in the rational
##  class of x with representatives x, x^k2, ..., x^km (in the order of the
##  entry of RationalClassSets(G) starting with i).
##  
# used internally for .exponents entries in RationalClassesInfo
InstallMethod(RatClassExps, ["IsGroup"],
function(G)
  local rs, pms, res, l, pm, a, j;
  rs := RationalClassSets(G);
  pms := PowerMapsOfAllClasses(G);
  res := [];
  for a in rs do
    # first class and class of its inverses
    l := [a[1]];
    pm := pms[a[1]];
    Add(l, pm[Length(pm)]);
    for j in [2..Length(a)] do
      Add(l, Position(pm, a[j])-1);
    od;
    Add(res, l);
  od;
  return res;
end);

##  A utility:
##  Every element in Q[E(n)] can be written as Q-linear combination of the
##  basis {E(n)^i| i=0..Phi(n)-1}. This function returns a list l of n integers
##  such that l[j] is the coefficient at E(n)^0=1 of E(n)^(j-1).
# for caching the results
BindGlobal("RATPARTVEC", []);
BindGlobal("RatPartVec", function(n)
  local cp, phi, res, v, i;
  if not IsBound(RATPARTVEC[n]) then
    cp := CyclotomicPol(n);
    phi := Length(cp)-1;
    res := 0*cp;
    res[1] := 1;
    res[phi+1] := -1;
    v := 0*cp;
    Add(v, 1);
    for i in [phi+1..n-1] do
      ReduceCoeffs(v, cp);
      Add(res, v[1]);
      v := Concatenation([0],v);
    od;
    RATPARTVEC[n] := res;
  fi;
  return RATPARTVEC[n];
end);


##  <#GAPDoc Label="RationalClassesInfo">
##  <ManSection>
##  <Attr Name="RationalClassesInfo" Arg="G"/>
##  <Returns>a list of records</Returns>
##  <Description>
##  Returns a list of records, one for each rational class of <A>G</A>
##  (see <Ref Attr="RationalClassSets"/>), in the same order. This
##  collects detailed information about the classes, used, for example,
##  to encode character values in an <Ref Filt="IsCCTable"/> object via
##  <Ref Func="EncodeForCCTable"/>.
##  <P/>
##  If the rational class consists of a single conjugacy class, say class
##  number <M>i</M>, the record has the components:
##  <List>
##  <Mark><C>classes</C></Mark>
##  <Item><C>[ i ]</C></Item>
##  <Mark><C>conductor</C></Mark>
##  <Item><C>1</C></Item>
##  <Mark><C>classlen</C></Mark>
##  <Item>the length of class <M>i</M></Item>
##  <Mark><C>order</C></Mark>
##  <Item>the order of the elements in class <M>i</M></Item>
##  <Mark><C>ind</C></Mark>
##  <Item>the position of the (rational) character value on this class in
##  a character encoded by <Ref Func="EncodeForCCTable"/></Item>
##  <Mark><C>exponents</C></Mark>
##  <Item><C>[ i, i ]</C></Item>
##  </List>
##  Otherwise, that is if the rational class consists of several
##  conjugacy classes, the record has the components:
##  <List>
##  <Mark><C>classes</C></Mark>
##  <Item>the list of numbers of the conjugacy classes in this rational
##  class (see <Ref Attr="RationalClassSets"/>)</Item>
##  <Mark><C>classlen</C></Mark>
##  <Item>the (common) length of these conjugacy classes</Item>
##  <Mark><C>order</C></Mark>
##  <Item>the (common) order of their elements</Item>
##  <Mark><C>conductor</C></Mark>
##  <Item>the smallest <C>k &gt; 1</C> such that the character values on
##  this rational class are contained in <M>\mathbb{Q}</M> extended by
##  <C>k</C>-th roots of unity</Item>
##  <Mark><C>ind</C></Mark>
##  <Item>the list of positions (of length <C>Phi(conductor)</C>) in a
##  character encoded by <Ref Func="EncodeForCCTable"/> which describe the
##  character values on this rational class</Item>
##  <Mark><C>cpol</C></Mark>
##  <Item>the coefficient list of the <C>conductor</C>-th cyclotomic
##  polynomial</Item>
##  <Mark><C>stabilizer</C></Mark>
##  <Item>a list of generating invertible residue classes mod <C>order</C>
##  which generate the stabilizer of the class under the unit group mod
##  <C>order</C></Item>
##  <Mark><C>field</C></Mark>
##  <Item>the field generated by the character values on this class</Item>
##  <Mark><C>dim</C></Mark>
##  <Item>the degree of <C>field</C> over the rationals</Item>
##  <Mark><C>exponents</C></Mark>
##  <Item><C>[ i, j, k1, ... ]</C>: if <C>x</C> is in class <M>i</M> then
##  <M>j</M> is the class of <C>x^-1</C>, and <C>x^k1</C>, ... are
##  representatives of the other classes in this rational class (ordered
##  as in <C>classes</C>)</Item>
##  <Mark><C>ratvec</C></Mark>
##  <Item>a sparse encoding of a vector related to the character values
##  on this class, see below</Item>
##  </List>
##  For <C>x</C> in the field generated by <C>E(k)</C> let <C>f(x)</C> be
##  the coefficient at <C>1</C> when <C>x</C> is written as a polynomial
##  modulo the <C>k</C>-th cyclotomic polynomial. Let <C>e = E(k)</C>,
##  <C>i</C> in <C>[0.. order-1]</C>, and let <C>x</C>, <C>x^k1</C>, ...
##  be representatives of the classes in the rational class of <C>x</C>.
##  Then let <C>l</C> be the list with
##  <C>l[i] = f(e^i + e^(i*k1) + ...)</C>. The component <C>ratvec</C> is
##  a sparse representation of <C>l</C>: the list
##  <C>[i1, l[i1], i2, l[i2], ...]</C>, where indices with <C>l[i] = 0</C>
##  are left out. (This data structure is used by a fast function for
##  computing scalar products of generalized characters.)
##  <Example>
##  gap> G := AlternatingGroup(5);;
##  gap> rci := RationalClassesInfo(G);;
##  gap> rci[2];
##  rec( classes := [ 2 ], classlen := 15, conductor := 1,
##    exponents := [ 2, 2 ], ind := 2, order := 2 )
##  gap> rci[4];
##  rec( classes := [ 4, 5 ], classlen := 12, conductor := 5,
##    cpol := [ 1, 1, 1, 1, 1 ], dim := 4, exponents := [ 4, 4, 2 ],
##    field := NF(5,[ 1, 4 ]), ind := [ 4 .. 7 ], order := 5,
##    ratvec := [ 0, 2, 2, -1, 4, -1 ], stabilizer := [ 1, 4 ] )
##  </Example>
##  </Description>
##  </ManSection>
##  <#/GAPDoc>
##  This function returns a list of records, each for one rational
##  class of G. If the rational class consists of one conjugacy class,
##  say class number i, the components are
##  
##    .classes     [i]
##    .conductor   1
##    .classlen    length of class
##    .order       order of elements in class i
##    .ind         position of character value (is in Q) on this class when
##                 character is encoded by EncodeForCCTable
##    .exponents   [i, i]
##  
##  Otherwise the components are
##  
##    .classes     [i, ...] numbers of conjugacy classes (see RationalClassSets)
##    .classlen    length of (each) conjugacy class
##    .order       order of elements in class
##    .conductor   smallest k (>1) such that character values are contained in
##                 Q extended by k-th roots of unity
##    .ind         list of positions in a character encoded by
##                 EncodeForCCTable which describe character value on class i
##                 (of length Phi(.conductor))
##    .cpol        coefficient list of k-th cyclotomic polynomial
##    .stabilizer  list of generating invertible residue classes mod .order
##                 which generate the stabilizer of the class under
##                 the unit group mod .order
##    .field       field generated by character values on this class
##    .dim         degree of .field over rationals
##    .exponents   [i, j, k1, ..., ] if x is in class i then j is class of
##                 x^-1, and x^k1, ... are representatives of other classes
##                 in rational class (ordered as in .classes)
##    .ratvec      list of integers, see below
##  
##  For x in the field generated by E(k) let f(x) be the coefficient
##  at 1 when x is written as polynomial modulo the k-th cyclotomic polynomial.
##  Let e = E(k), i in [0.. .order-1], and x in class i and x, x^k1, ...
##  representatives of the classes in rational class of x. Then let l be
##  the list where l[i] = f(e^i + e^(i*k1) + ...).
##  The entry .ratvec is a sparse representation of l: [i1,l[i1], i2, l[i2],
##  ...] where the indices with l[i] = 0 are left out.
##  
InstallMethod(RationalClassesInfo, ["IsGroup"], function(G)
  local cl, pms, rc, rce, ords, res, last, sparsify, r, 
        pm, o, st, c, rv, e, i;
  cl := ConjugacyClasses(G);
  pms := PowerMapsOfAllClasses(G);
  rc := RationalClassSets(G);
  rce := RatClassExps(G);
  ords := OrdersClassRepresentatives(G);
  res := [];
  last := 0;
  # sparse representation of vector
  sparsify := function(v)
    local res, i;
    res := [];
    for i in [1..Length(v)] do
      if v[i]<>0 then
        Add(res, i);
        Add(res, v[i]);
      fi;
    od;
    return res;
  end;
  for i in [1..Length(rc)] do
    r := rec(classes := rc[i],
             exponents := rce[i],
             order := ords[rc[i][1]],
             classlen := Size(cl[rc[i][1]]));
    if Length(rc[i]) = 1 then
      r.conductor := 1;
      r.ind := last+1;
      last := last+1;
    else
      pm := pms[rc[i][1]];
      o := ords[rc[i][1]];
      # Galois stabilizer of class and character field
      st := Positions(pm, pm[2])-1;
      r.order := o;
      r.field := NF(o, st);
      c := Conductor(r.field);
      r.conductor := c;
      r.cpol := CyclotomicPol(c);
      r.dim := Length(r.cpol)-1;
      # adjust stabilizer if conductor is smaller than o
      if c < o then
        st := Set(st mod c);
      fi;
      r.stabilizer := st;
      r.ind := [last+1..last+r.dim];
      last := last+r.dim;
      rv := RatPartVec(c);
      e := Concatenation([1], r.exponents{[3..Length(r.exponents)]});
      # in position i the rational coefficient of
      # Sum(e, k-> E(r.conductor)^(i*k)) wrt. cyclotomic polynomial
      r.ratvec := sparsify(List([0..c-1], i-> Sum(rv{(i*e mod c)+1}))); 
      for i in [1,3..Length(r.ratvec)-1] do
        r.ratvec[i] := r.ratvec[i]-1;
      od;
    fi;
    Add(res, r);
  od;
  return res;
end);


##  <#GAPDoc Label="PowerMapCharacters">
##  <ManSection>
##  <Func Name="PowerMapCharacters" Arg="G, n"/>
##  <Returns>a list of row lists of integers</Returns>
##  <Description>
##  This function returns a list of class functions on the finite group <A>G</A>
##  (as lists of values in the order of the conjugacy classes in <A>G</A>), 
##  associated to the map <M>g \mapsto g^{<A>n</A>}</M> on
##  <A>G</A>. For each rational class <M>C</M> of <A>G</A>, the class function
##  has value <M>|G|/\gcd(|G|,n)</M> on elements <M>x</M> with <M>x^n \in
##  C</M>, and <M>0</M> everywhere else. According to a theorem of Frobenius (see 
##  <Cite Key="Serre77" Where="Section 11.2"/>) these class functions are 
##  generalized characters (we sum the functions in the cited reference over all
##  conjugacy classes in a rational class to get rational integer coefficients).
##  <P/>
##  Only the non-zero class functions (for rational classes in the image of
##  <M>g \mapsto g^{<A>n</A>}</M>) are returned.
##  <Example>
##  gap> G := AlternatingGroup(5);;
##  gap> pmchars := PowerMapCharacters(G, 2);
##  [ [ 30, 30, 0, 0, 0 ], [ 0, 0, 30, 0, 0 ], [ 0, 0, 0, 30, 30 ] ]
##  gap>
##  gap> MatScalarProducts(Irr(G), pmchars);
##  [ [ 8, 2, 10, -6, -6 ], [ 10, 10, -10, 0, 0 ], [ 12, -12, 0, 6, 6 ] ]
##  </Example>
##  </Description>
##  </ManSection>
##  <#/GAPDoc>
##  Here we use a theorem of Frobenius as explained in
##  Serre, Linear representations of finite groups, Section 11.2
##
##  For a positive integer n and a rational class C of the group G the class
##  function with value |G|/gcd(|G|,n) on elements x with x^n in  C and 0
##  anywhere else is a generalized character (Theorem 23 in loc.cit. is finer,
##  but we sum over all classes in a rational class to get rational
##  integer coefficients).
##
##  This function returns for G and n the just described class functions for all
##  classes with non-empty preimages.
##
BindGlobal("PowerMapCharacters", function(G, n)
  local t, pm, ords, k, sz, l, s, c, rc, res, ch, pos, a;
  #t := CharacterTable(G);
  pm := PowerMapsOfAllClasses(G);
  ords := List(pm, Length);
  k := Length(pm);
  sz := Size(G);
  l := List([1..k], i-> pm[i][(n mod ords[i])+1]);
  s := Set(l);
  c := sz/Gcd(sz, n);
  rc := RationalClassSets(G);
  res := [];
  for a in rc do
    if a[1] in s then
      ch := 0*[1..k];
      pos := Concatenation(List(a, i-> Positions(l, i)));
      ch{pos} := ch{pos}+c;
      #Add(res, Character(t, ch));
      Add(res, ch);
    fi;
  od;
  return res;
end);

##  <#GAPDoc Label="SmallPowerMapCharacters">
##  <ManSection>
##  <Func Name="SmallPowerMapCharacters" Arg="G"/>
##  <Returns>a list of row vectors of integers</Returns>
##  <Description>
##  Applies <Ref Func="PowerMapCharacters"/> for a selection of divisors
##  <M>n</M> of <M>|<A>G</A>|</M> that are large (so that the value
##  <M>|<A>G</A>|/\gcd(|<A>G</A>|,n)</M> occurring in
##  <Ref Func="PowerMapCharacters"/> is small but non-zero), one <M>n</M>
##  associated to each element order occurring in <A>G</A>. 
##  Class functions with the same
##  pattern of zero entries are reduced to the one with (componentwise)
##  minimal non-zero values.
##  <Example>
##  gap> G := AlternatingGroup(5);;
##  gap> SmallPowerMapCharacters(G);
##  [ [ 0, 0, 0, 5, 5 ], [ 0, 0, 3, 0, 0 ], [ 0, 4, 0, 0, 0 ],
##    [ 4, 0, 4, 4, 4 ], [ 3, 3, 0, 3, 3 ], [ 5, 5, 5, 0, 0 ] ]
##  </Example>
##  </Description>
##  </ManSection>
##  <#/GAPDoc>
##  Here we use the previous function for some large divisors of |G| (that is
##  small non-zero values) associated to the element orders in G.
BindGlobal("SmallPowerMapCharacters", function(G)
  local pm, orders, sz, e, fac, ns, o, f, n, l, ps, res, pos, i, a;
  pm := PowerMapsOfAllClasses(G);
  orders := Set(List(pm, Length));
  sz := Size(G);
  e := Lcm(orders);
  fac := Collected(Factors(sz));
  ns := [];
  for i in [2..Length(orders)] do
    o := orders[i];
    f := Set(Factors(o));
    n := Product(List(Filtered(fac, a-> not a[1] in f), b-> b[1]^b[2]));
    Add(ns, n);
    while Gcd(sz, n*o) mod e <> 0 do
      n := n*o;
      Add(ns, n);
    od;
  od;
  l := Concatenation(List(Set(ns), n-> PowerMapCharacters(G, n)));
  # Some functions can have the same pattern of zero entries, we
  # only keep those with minimal non-zero values.
  ps := List(l, a-> Positions(a,0));
  res := [];
  for a in Set(ps) do
    pos := Positions(ps, a);
    Add(res, Minimum(l{pos}));
  od;
  return res;
end);

##  <#GAPDoc Label="ActionAutomorphismsOnConjugacyClasses">
##  And here is a utility function that makes use of <Ref
##  Func="PowerMapsOfAllClasses"/>.
##  <ManSection>
##  <Func Name="ActionAutomorphismsOnConjugacyClasses" Arg="G, A"/>
##  <Func Name="ActionAutomorphismsOnRationalClasses" Arg="G, A"/>
##  <Returns>a permutation group</Returns>
##  <Description>
##  Let <A>A</A> be a group of automorphisms of <A>G</A> (for example
##  <C>AutomorphismGroup(<A>G</A>)</C>). The first function returns the
##  permutation group describing the induced action of <A>A</A> on
##  the conjugacy classes of <A>G</A> (identified by their position in
##  <C>ConjugacyClasses(<A>G</A>)</C>). The generators of the
##  result correspond to <C>GeneratorsOfGroup(<A>A</A>)</C>.
##  <P/>
##  The second function returns the permutation group for the induced
##  action on the rational classes of <A>G</A>.
##  <P/>
##  The first function finds the classes of the images of generators of
##  maximal cyclic subgroups and deduces the rest from 
##  <Ref  Func="PowerMapsOfAllClasses"/> for <A>G</A>.
##  <Example><![CDATA[
##  gap> G := AlternatingGroup(5);;
##  gap> A := AutomorphismGroup(G);
##  <group of size 120 with 3 generators>
##  gap> ActionAutomorphismsOnConjugacyClasses(G, A);
##  Group([ (4,5), (), () ])
##  gap> ActionAutomorphismsOnRationalClasses(G, A);
##  Group(())
##  ]]></Example>
##  </Description>
##  </ManSection>
##  <#/GAPDoc>
BindGlobal("ActionAutomorphismsOnConjugacyClasses", function(G, A)
  local gens, agens, cl, pms, mc, excl, l, x, pos, pm, pmp, k, a, i, j;
  gens := [];
  agens := GeneratorsOfGroup(A);
  cl := ConjugacyClasses(G);
  # it is sufficient to find images of generators of maximal cyclic
  # subgroups, the remaining map follows from the power maps
  pms := PowerMapsOfAllClasses(G);
  mc := MaximalCyclics(G);
  for a in agens do
    excl := [];
    l := [];
    for i in mc do
      x := Representative(cl[i]);
      pos := PositionConjugacyClass(G, x^a, excl);
      pm := pms[i];
      pmp := pms[pos];
      for j in [1..Length(pm)] do
        k := pm[j];
        if not IsBound(l[k]) then
          l[k] := pmp[j];
          AddSet(excl, pmp[j]);
        fi;
      od;
    od;
    Add(gens, PermList(l));
  od;
  return Group(gens);
end);

# induced permutation action on rational classes
BindGlobal("ActionAutomorphismsOnRationalClasses", function(G, A)
  local rcs, rcrep, v, a, gc, gens, i;
  rcs := RationalClassSets(G);
  rcrep := List(rcs, x-> x[1]);
  v := [];
  for i in [1..Length(rcs)] do
    a := rcs[i];
    v{a} := 0*a+i;
  od;
  gc := GeneratorsOfGroup(ActionAutomorphismsOnConjugacyClasses(G, A));
  gens := List(gc, x-> PermList(v{List(rcrep, i-> i^x)}));
  return Group(gens);
end);


